// <copyright company="Microsoft Corporation">
//   Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
namespace Microsoft.Membership.MemberServices.PrivacyExperience.FunctionalTests
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Reflection;
    using System.Threading;

    using Microsoft.Membership.MemberServices.PrivacyExperience.Test.Common;

    /// <summary>
    ///     Test User
    /// </summary>
    public class TestUsers
    {
        private static readonly Lazy<IList<TestUser>> lazyTestUsers = new Lazy<IList<TestUser>>(
            () =>
            {
                // Loads test users from file
                Assembly assembly = Assembly.GetExecutingAssembly();
                string resourceName = "Microsoft.Membership.MemberServices.PrivacyExperience.FunctionalTests.Int_Accounts.txt";

                // Use for debugging if manifest can't be found.
                // var manifestResources = assembly.GetManifestResourceNames();
                // Console.WriteLine($"Embedded resource names: {string.Join(",", manifestResources)}");

                var lines = new List<string>();
                using (Stream stream = assembly.GetManifestResourceStream(resourceName))
                {
                    using (var reader = new StreamReader(stream ?? throw new InvalidOperationException($"resource name not found: {resourceName}")))
                    {
                        while (!reader.EndOfStream)
                        {
                            lines.Add(reader.ReadLine());
                        }
                    }
                }

                var users = new List<TestUser>();
                foreach (string line in lines)
                {
                    string[] lineSplit = line.Split(new[] { ',' }, StringSplitOptions.RemoveEmptyEntries);
                    users.Add(new TestUser(lineSplit[0], lineSplit[1], long.Parse(lineSplit[2], NumberStyles.AllowHexSpecifier)));
                }

                return users;
            },
            LazyThreadSafetyMode.PublicationOnly);

        // NOTE: Test accounts are generated by MSA as unprotected, from:
        // https://identitydivision.visualstudio.com/CAT/_workitems?id=320031&_a=edit

        public static TestUser CortanaNotebook0
        {
            get { return TestUsersArray[0]; }
        }

        public static TestUser DeleteBrowse0
        {
            get { return TestUsersArray[1]; }
        }

        public static TestUser DeleteLocation0
        {
            get { return TestUsersArray[2]; }
        }

        public static TestUser DeleteSearch0
        {
            get { return TestUsersArray[3]; }
        }

        public static TestUser DeleteVoice0
        {
            get { return TestUsersArray[4]; }
        }

        public static TestUser PrivacyTest12
        {
            get { return TestUsersArray[5]; }
        }

        public static TestUser TimelineDeleteById
        {
            get { return TestUsersArray[6]; }
        }

        public static TestUser TimelineDeleteByType
        {
            get { return TestUsersArray[7]; }
        }

        public static TestUser UpdateSettings0
        {
            get { return TestUsersArray[8]; }
        }

        public static TestUser UpdateSettings1
        {
            get { return TestUsersArray[9]; }
        }

        public static TestUser UpdateSettings2
        {
            get { return TestUsersArray[10]; }
        }

        public static TestUser UpdateSettings3
        {
            get { return TestUsersArray[11]; }
        }

        public static TestUser ViewBrowse0
        {
            get { return TestUsersArray[12]; }
        }

        public static TestUser ViewLocation0
        {
            get { return TestUsersArray[13]; }
        }

        public static TestUser ViewSearch0
        {
            get { return TestUsersArray[14]; }
        }

        public static TestUser ViewSettings0
        {
            get { return TestUsersArray[15]; }
        }

        public static TestUser ViewVoice0
        {
            get { return TestUsersArray[16]; }
        }

        public static TestUser AadAuthTestUser
        {
            get { return TestUsersArray[17]; }
        }

        public static TestUser Verifier001
        {
            get { return TestUsersArray[18]; }
        }

        public static TestUser Parent1
        {
            get => TestUsersArray[19];
        }

        public static TestUser Child1
        {
            get => TestUsersArray[20];
        }

        public static TestUser Child2
        {
            get => TestUsersArray[21];
        }
        private static IList<TestUser> TestUsersArray
        {
            get { return lazyTestUsers.Value; }
        }
    }
}
