//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//
// This source code was auto-generated by xsd, Version=4.6.1055.0.
//
namespace Microsoft.Membership.MemberServices.Privacy.Core.AQS {
    using System.Xml.Serialization;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class CDPEvent2 {

        private int versionField;

        private string aggregationKeyField;

        private long sequenceNumberField;

        private EventData eventDataField;

        /// <remarks/>
        public int Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }

        /// <remarks/>
        public string AggregationKey {
            get {
                return this.aggregationKeyField;
            }
            set {
                this.aggregationKeyField = value;
            }
        }

        /// <remarks/>
        public long SequenceNumber {
            get {
                return this.sequenceNumberField;
            }
            set {
                this.sequenceNumberField = value;
            }
        }

        /// <remarks/>
        public EventData EventData {
            get {
                return this.eventDataField;
            }
            set {
                this.eventDataField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AccountNameVersionUpdate))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RelationshipDelete))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RelationshipUpdate))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RelationshipCreate))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AliasDelete))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AliasUpdate))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AliasCreate))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DeviceDelete))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DeviceUpdate))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DeviceCreate))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UserDelete))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UserUpdate))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UserCreate))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EventData : EventDataBase {
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EventData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AccountNameVersionUpdate))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RelationshipDelete))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RelationshipUpdate))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RelationshipCreate))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AliasDelete))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AliasUpdate))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AliasCreate))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DeviceDelete))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DeviceUpdate))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DeviceCreate))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UserDelete))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UserUpdate))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UserCreate))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public abstract partial class EventDataBase {

        private EventDataBaseProperty[] propertyField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Property")]
        public EventDataBaseProperty[] Property {
            get {
                return this.propertyField;
            }
            set {
                this.propertyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class EventDataBaseProperty {

        private string nameField;

        private string valueField;

        private string oldValueField;

        private string flagsField;

        private string oldFlagsField;

        private string extendedDataField;

        private string credentialTypeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OldValue {
            get {
                return this.oldValueField;
            }
            set {
                this.oldValueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Flags {
            get {
                return this.flagsField;
            }
            set {
                this.flagsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OldFlags {
            get {
                return this.oldFlagsField;
            }
            set {
                this.oldFlagsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ExtendedData {
            get {
                return this.extendedDataField;
            }
            set {
                this.extendedDataField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CredentialType {
            get {
                return this.credentialTypeField;
            }
            set {
                this.credentialTypeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AccountNameVersionUpdate : EventData {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RelationshipDelete : EventData {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RelationshipUpdate : EventData {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RelationshipCreate : EventData {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AliasDelete : EventData {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AliasUpdate : EventData {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AliasCreate : EventData {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeviceDelete : EventData {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeviceUpdate : EventData {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeviceCreate : EventData {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UserDelete : EventData {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UserUpdate : EventData {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UserCreate : EventData {
    }
}
