// --------------------------------------------------------------------
// <auto-generated>
// This is a CDP xPlat pipeline generated file for managed C# projects.
// </auto-generated>
// --------------------------------------------------------------------

using System.Reflection;
[assembly: AssemblyVersion("2.5.2055.000")]
[assembly: AssemblyFileVersion("2.5.2055.000")]
[assembly: AssemblyInformationalVersion("2.5.2055.000-pcfsdk")]