// <auto-generated />
// <copyright>Copyright (c) Microsoft Corporation. All rights reserved.</copyright>

using Microsoft.CommonSchema.Services.Logging;
using Microsoft.CommonSchema.Services.Owin;

namespace Microsoft.PrivacyServices.CommandFeed.Service.Instrumentation
{
    /// <summary>
    /// SLL policy container class. Do not edit.
    /// </summary>
    public partial class Policies : PolicyRegistration
    {
        /// <summary>
        /// Gets the policy configuration for an Owin-based service.
        /// </summary>
        public static OwinPolicy Owin
        {
            get
            {
                return Single<OwinPolicy>.Current;
            }
        }
    }
}
