#################################################################################
#                        OneBranch Pipelines - Buddy                            #
# This pipeline was created by EasyStart from a sample located at:              #
#   https://aka.ms/obpipelines/easystart/samples                                #
# Documentation:  https://aka.ms/obpipelines                                    #
# Yaml Schema:    https://aka.ms/obpipelines/yaml/schema                        #
# Retail Tasks:   https://aka.ms/obpipelines/tasks                              #
# Support:        https://aka.ms/onebranchsup                                   #
#################################################################################

trigger: none

parameters:
- name: debug
  displayName: Enable debug output
  type: boolean
  default: false

variables:
- template: variables.yml


resources:
  repositories: 
    - repository: templates
      type: git
      name: OneBranch.Pipelines/GovernedTemplates
      ref: refs/heads/main

extends:
  template: v2/OneBranch.NonOfficial.CrossPlat.yml@templates
  parameters:
    featureFlags:
      ensureArtifactsDirExists: true
    cloudvault:
      enabled: false
    globalSdl: # https://aka.ms/obpipelines/sdl
      sbom:
        enabled: true
      binskim:
        break: true
        analyzeTargetGlob: 
          '+:file|src\NGPProxy\**\*;-:file|**\IniFlatten.exe;-:file|**\ConvertToPlayableAudio.dll;-:file|**\Microsoft.Azure.DataLake.Store.dll;-:file|**\Microsoft.Azure.KeyVault.Core.dll;-:file|**\Microsoft.IdentityModel.Tokens.JWT.dll;-:file|**\Microsoft.Practices.ServiceLocation.dll;-:file|**\Microsoft.Practices.TransientFaultHandling.Core.dll'
      credscan:
        enabled: false
      policheck:
        break: true 
      tsa:
        # If TSA is disabled all SDL tools will be forced into 'break' build mode.
        enabled: false 

    stages:
    - stage: build
      jobs:
      - job: main
        pool:
          type: windows
        variables: 
          # More settings at https://aka.ms/obpipelines/yaml/jobs
          ob_outputDirectory: $(Build.SourcesDirectory)\src\NGPProxy\OneBranch\Deployment\drop
          ob_sdl_binskim_break: true # https://aka.ms/obpipelines/sdl

        steps:
          - template: .pipelines/HelperTemplates/version.restore.build.test.yml@self
            parameters:
              buildConfiguration: Debug
              productName: NGPProxy
              pathToRestore: $(NGPProxySolution)
