#################################################################################
#                        OneBranch Pipelines - Buddy                            #
# This pipeline was created by EasyStart from a sample located at:              #
#   https://aka.ms/obpipelines/easystart/samples                                #
# Documentation:  https://aka.ms/obpipelines                                    #
# Yaml Schema:    https://aka.ms/obpipelines/yaml/schema                        #
# Retail Tasks:   https://aka.ms/obpipelines/tasks                              #
# Support:        https://aka.ms/onebranchsup                                   #
#################################################################################

trigger: 
- master

parameters:
- name: 'debug'
  displayName: 'Enable debug output'
  type: boolean
  default: false

variables:
  # needed for onebranch.pipeline.version task https://aka.ms/obpipelines/versioning
  CDP_DEFINITION_BUILD_COUNT: $[counter('', 0)]
  system.debug: ${{ parameters.debug }}
  ENABLE_PRS_DELAYSIGN: 0
  NUGET_XMLDOC_MODE: none
  WindowsContainerImage: 'onebranch.azurecr.io/windows/ltsc2019/vse2022:latest'

resources:
  repositories: 
    - repository: templates
      type: git
      name: OneBranch.Pipelines/GovernedTemplates
      ref: refs/heads/main

extends:
  template: v2/OneBranch.Official.CrossPlat.yml@templates
  parameters:
    cloudvault:
      enabled: true
    featureFlags:
      ensureArtifactsDirExists: true
    globalSdl:
      sbom:
        enabled: true
      antimalwareScan:
        enabled: false
      binskim:
        enabled: true
        break: true 
      codeql:
        cadence: 0
        compiled: 
          enabled: true
        tsaEnabled: true # See 'Codeql.TSAEnabled' in the Addition Options section below
      credscan:
        enabled: true
        suppressionsFile: $(Build.SourcesDirectory)\.config\CredScanSuppressions.json
      policheck:
        enabled: false
      tsa:
        enabled: true
        configFile: $(Build.SourcesDirectory)/.config/tsaoptions.json

    stages:
    - stage: build
      jobs:
      - job: main
        pool:
          type: windows 
        variables:
          ob_outputDirectory: $(Build.SourcesDirectory)\src\PXS\OneBranch\Deployment\drop
          ob_sdl_binskim_break: true
          ob_sdl_codeSignValidation_excludes: -|**\*\Newtonsoft.Json.dll;-|**\*.nupkg\**\*;-|**\*\Microsoft.Membership.MemberServices.Privacy.ExperienceContracts.dll
          ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}:
            ob_symbolsPublishing_enabled: true 

        steps:
          - template: .pipelines/HelperTemplates/version.restore.build.test.yml@self
            parameters:
              buildConfiguration: Release
              versionTemplate: onebranch.versioning.pxs.client.yml
              productName: PXS
              pathToRestore: $(Build.SourcesDirectory)\src\PXS\Product\PrivacyExperienceSvc.sln
              projectsToBuild:   
                - $(Build.SourcesDirectory)\src\PXS\Product\Contracts\PCFContracts\PXS.Command.Contracts.csproj
                - $(Build.SourcesDirectory)\src\PXS\Product\PXF\PrivacyExperienceClientLibrary\Source\PrivacyExperienceClientLibrary.csproj

          - task: onebranch.pipeline.signing@1
            displayName: Sign binaries
            inputs:
              command: sign
              signing_environment: azure-ado
              signing_profile: external_distribution
              files_to_sign: '**/*.exe;**/*.dll;**/*.ps1'
              search_root: $(Build.SourcesDirectory)\src\pxs\bin

          - task: onebranch.pipeline.signing@1
            displayName: Sign nupkgs
            inputs:
              command: sign
              signing_environment: azure-ado
              signing_profile: external_distribution
              files_to_sign: '**/*.nupkg'
              search_root: $(Build.SourcesDirectory)\src\PXS\nupkgs

          - template: .pipelines/HelperTemplates/pxs.client.package.yml@self
            parameters:
              packageSuffix: PROD
