#################################################################################
#                        OneBranch Pipelines - Buddy                            #
# This pipeline was created by EasyStart from a sample located at:              #
#   https://aka.ms/obpipelines/easystart/samples                                #
# Documentation:  https://aka.ms/obpipelines                                    #
# Yaml Schema:    https://aka.ms/obpipelines/yaml/schema                        #
# Retail Tasks:   https://aka.ms/obpipelines/tasks                              #
# Support:        https://aka.ms/onebranchsup                                   #
#################################################################################
trigger: none # https://aka.ms/obpipelines/triggers

parameters:
- name: debug
  displayName: Enable debug output
  type: boolean
  default: false

variables:
- template: variables.yml

resources:
  repositories: 
    - repository: templates
      type: git
      name: OneBranch.Pipelines/GovernedTemplates
      ref: refs/heads/main
    - repository: self
      type: git
      ref: refs/heads/master

extends:
  template: v2/OneBranch.NonOfficial.CrossPlat.yml@templates # https://aka.ms/obpipelines/templates
  parameters:
    featureFlags:
      ensureArtifactsDirExists: true
    globalSdl: # https://aka.ms/obpipelines/sdl
      sbom:
        enabled: true
      antimalwareScan:
        enabled: false
      binskim:
        enabled: true
        break: true 
      credscan:
        enabled: false
      ESLint:
        enabled: false
      policheck:
        policheckExclusionsPath: (OneBranch.ProductDirectory)\Product\Source\ux\appsettings.json
      tsa:
        # If TSA is disabled all SDL tools will forced into 'break' build mode.
        enabled: false 

    stages:
    - stage: build
      jobs:
      - job: main
        pool:
          type: windows
        variables:
          ob_outputDirectory: $(OneBranch.DeploymentDirectory)\drop
          ob_artifactBaseName: drop

        steps:              
          - template: .pipelines/HelperTemplates/version.restore.build.test.yml@self
            parameters:
              buildConfiguration: Debug
              productName: PAF
              pathToRestore: $(PAFSolution)
