#################################################################################
#                      OneBranch Pipelines - PR Build                           #
# This pipeline was created by EasyStart from a sample located at:              #
#   https://aka.ms/obpipelines/easystart/samples                                #
# Documentation:  https://aka.ms/obpipelines                                    #
# Yaml Schema:    https://aka.ms/obpipelines/yaml/schema                        #
# Retail Tasks:   https://aka.ms/obpipelines/tasks                              #
# Support:        https://aka.ms/onebranchsup                                   #
#################################################################################
trigger: none # https://aka.ms/obpipelines/triggers

parameters:
- name: debug
  displayName: Enable debug output
  type: boolean
  default: false

variables:
- template: variables.yml

resources:
  repositories: 
    - repository: templates
      type: git
      name: OneBranch.Pipelines/GovernedTemplates
      ref: refs/heads/main

extends:
  template: v2/OneBranch.NonOfficial.CrossPlat.yml@templates
  parameters:
    featureFlags:
      ensureArtifactsDirExists: true
    globalSdl:
      sbom:
        enabled: true
      antiMalwareScan:
        enabled: true
      binskim:
        break: true
        analyzeTargetGlob:
          '+:file|**\Microsoft.PrivacyServices*.exe;+:file|**\Microsoft.PrivacyServices*.dll;+:file|**\Pxs*.exe;+:file|**\Pxs*.dll;+:file|**\Microsoft.Azure.ComplianceServices*.exe;+:file|**\Microsoft.Azure.ComplianceServices*.dll;+:file|**\CertInstaller*.exe;+:file|**\CertInstaller*.dll'
      credscan:
        enabled: false
      policheck:
        break: false 
      tsa:
        # If TSA is disabled all SDL tools will forced into 'break' build mode.
        enabled: false

    stages:
    - stage: build
      jobs:
      - job: main
        pool:
          type: windows
        variables: 
          ob_outputDirectory: $(PXSOutputDirectory)

        steps:
          - template: .pipelines/HelperTemplates/version.restore.build.test.yml@self
            parameters:
              buildConfiguration: Debug
              productName: PXS
              pathToRestore: $(PXSSolution)
