#################################################################################
#                      OneBranch Pipelines - PR Build                           #
# This pipeline was created by EasyStart from a sample located at:              #
#   https://aka.ms/obpipelines/easystart/samples                                #
# Documentation:  https://aka.ms/obpipelines                                    #
# Yaml Schema:    https://aka.ms/obpipelines/yaml/schema                        #
# Retail Tasks:   https://aka.ms/obpipelines/tasks                              #
# Support:        https://aka.ms/onebranchsup                                   #
#################################################################################

trigger:
  branches:
    include:
    - develop
  paths:
    include:
    - /*
    - src/PCF/Product/Libraries/PrivacyCommandValidator
    - src/PCF/Product/Client/Source
    - src/PDMS/Product/ClientSdks/Client
    exclude:
    - src/PAF/*
    - src/PCF/*
    - src/PCD/*
    - src/PDMS/*
    - src/NGPProxy/*

parameters:
- name: debug
  displayName: Enable debug output
  type: boolean
  default: false 

variables:
- template: variables.yml

resources:
  repositories: 
    - repository: templates
      type: git
      name: OneBranch.Pipelines/GovernedTemplates
      ref: refs/heads/main

extends:
  template: v2/OneBranch.NonOfficial.CrossPlat.yml@templates 
  parameters:
    cloudvault:
      enabled: true
    featureFlags:
      ensureArtifactsDirExists: true
    globalSdl:
      sbom:
        enabled: true
      antiMalwareScan:
        enabled: true
      binskim:
        break: true 
        analyzeTargetGlob: 
          '+:file|**\Microsoft.PrivacyServices*.exe;+:file|**\Microsoft.PrivacyServices*.dll;+:file|**\Pxs*.exe;+:file|**\Pxs*.dll;+:file|**\Microsoft.Azure.ComplianceServices*.exe;+:file|**\Microsoft.Azure.ComplianceServices*.dll;+:file|**\CertInstaller*.exe;+:file|**\CertInstaller*.dll'
      credscan:
        enabled: true
        suppressionsFile: $(CREDSCAN_SUPPRESSIONFILE)
      policheck:
        break: true 
      tsa:
        enabled: false
        configFile: $(TSA_CONFIGFILE)

    stages:
    - stage: build
      jobs:
      - job: main
        pool:
          type: windows  
        variables: 
          ob_outputDirectory: $(PXSOutputDirectory)
          ob_sdl_binskim_break: true

        steps:
          - template: .pipelines/HelperTemplates/version.restore.build.test.yml@self
            parameters:
              buildConfiguration: Release
              productName: PXS
              pathToRestore: $(PXSSolution)

          - task: CmdLine@2
            displayName: Restore packages for OpenApi generator
            inputs:
              script: $(Build.SourcesDirectory)\.build\restoreopenapi.cmd

          - task: CmdLine@2
            displayName: Build OpenApi doc
            inputs:
              script: $(Build.SourcesDirectory)\.build\buildopenapi.cmd Debug
            env:
              CDP_BUILD_TAG: PXS

          - template: .pipelines/HelperTemplates/pxs.package.yml@self
